# Generated by Django 3.2.13 on 2022-06-15 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sys_user',
            old_name='mobile',
            new_name='mobile_phone',
        ),
        migrations.AlterField(
            model_name='sys_user',
            name='email',
            field=models.EmailField(max_length=32, verbose_name='邮箱'),
        ),
    ]
